document.write("<br>");
document.write("<br>");
document.write("<b>");
document.write("Task#07");
document.write("<br>");
document.write("<b>");
document.write("Rules For naming Js Variables");
document.write("</b>");
document.write("<br>");
document.write("<br>");
document.write("<b>");
document.write("Variables names can only contain, Numbers, $ and _. For Example: $My_1stvariable.");
document.write("<br>");
document.write("Variable must begin with a letter, $, or _. For Example: $name, _name, or name.");
document.write("<br>");
document.write("variable names are case sensitive.  ");
document.write("<br>");
document.write("Variables names should not be Js keywords. ");
document.write("</b>");
document.write("<br>");
document.write("<br>");